import os
import base64
import logging
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont
import requests
import aiohttp
import asyncio

logger = logging.getLogger(__name__)

class ImageGenerator:
    def __init__(self, config):
        self.config = config
        self.temp_dir = "temp"
        os.makedirs(self.temp_dir, exist_ok=True)
    
    async def generate(self, campaign_details: str, style: str, color: str,
                      width: int, height: int, logo_path: str = None):
        """Generate campaign image"""
        try:
            # Try using external API if available
            if self.config.OPENAI_API_KEY:
                return await self.generate_with_openai(campaign_details, style, color, width, height)
            
            # Fallback to PIL generation
            return await self.generate_with_pil(campaign_details, style, color, width, height, logo_path)
            
        except Exception as e:
            logger.error(f"Image generation error: {e}")
            return {
                'success': False,
                'error': str(e)
            }
    
    async def generate_with_openai(self, details: str, style: str, color: str, width: int, height: int):
        """Generate image using OpenAI DALL-E"""
        try:
            import openai
            openai.api_key = self.config.OPENAI_API_KEY
            
            # Create prompt
            prompt = self.build_prompt(details, style, color)
            
            response = openai.Image.create(
                prompt=prompt,
                n=1,
                size=f"{width}x{height}",
                response_format="b64_json"
            )
            
            image_data = response['data'][0]['b64_json']
            
            return {
                'success': True,
                'image_data': image_data,
                'image_url': None
            }
        except Exception as e:
            logger.error(f"OpenAI generation error: {e}")
            return {
                'success': False,
                'error': str(e)
            }
    
    async def generate_with_pil(self, details: str, style: str, color: str,
                               width: int, height: int, logo_path: str = None):
        """Generate image using PIL (fallback)"""
        try:
            # Create background
            bg_color = self.get_color_palette(color)
            image = Image.new('RGB', (width, height), bg_color)
            draw = ImageDraw.Draw(image)
            
            # Add gradient or pattern based on style
            self.apply_style_effect(image, draw, style, width, height)
            
            # Add border
            draw.rectangle([(20, 20), (width-20, height-20)], outline='white', width=2)
            
            # Add text
            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 40)
                font_small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 24)
            except:
                font = ImageFont.load_default()
                font_small = ImageFont.load_default()
            
            # Add campaign details
            lines = self.wrap_text(details, width - 100, font)
            y = height // 2 - len(lines) * 25
            for line in lines[:5]:  # Limit to 5 lines
                draw.text((width//2, y), line, fill='white', font=font, anchor="mm")
                y += 40
            
            # Add footer
            draw.text((width//2, height-50), "Generated by PromoCanvas", 
                     fill='white', font=font_small, anchor="mm")
            
            # Save image to bytes
            img_bytes = BytesIO()
            image.save(img_bytes, format='PNG')
            img_data = base64.b64encode(img_bytes.getvalue()).decode('utf-8')
            
            return {
                'success': True,
                'image_data': img_data,
                'image_url': None
            }
            
        except Exception as e:
            logger.error(f"PIL generation error: {e}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def build_prompt(self, details: str, style: str, color: str) -> str:
        """Build prompt for AI image generation"""
        style_descriptions = {
            'modern': 'modern, minimalist, clean design',
            'artistic': 'artistic, creative, expressive design',
            'corporate': 'professional, corporate, business design',
            'vibrant': 'vibrant, energetic, bold design',
            'photo': 'photographic, high-quality, realistic design',
            'typography': 'typographic, text-focused, elegant design'
        }
        
        style_desc = style_descriptions.get(style, 'professional design')
        
        prompt = f"""
        Create a professional marketing campaign design with the following specifications:
        
        Style: {style_desc}
        Color scheme: {color}
        Content: {details}
        
        The design should be suitable for digital marketing and promotional use.
        Include appropriate visual elements and typography.
        """
        
        return prompt.strip()
    
    def get_color_palette(self, color_name: str):
        """Get color palette based on selection"""
        palettes = {
            'blue': (41, 128, 185),
            'red': (192, 57, 43),
            'green': (39, 174, 96),
            'warm': (211, 84, 0),
            'dark': (44, 62, 80),
            'bright': (241, 196, 15)
        }
        return palettes.get(color_name, (52, 73, 94))
    
    def apply_style_effect(self, image, draw, style, width, height):
        """Apply style-specific effects"""
        if style == 'modern':
            # Add minimalist shapes
            draw.rectangle([(width//4, 50), (width*3//4, 100)], fill='white', outline=None)
        elif style == 'artistic':
            # Add artistic circles
            for i in range(5):
                x = (i + 1) * width // 6
                draw.ellipse([(x-30, height//2-30), (x+30, height//2+30)], 
                           outline='white', width=2)
        elif style == 'corporate':
            # Add corporate lines
            draw.line([(50, height//2), (width-50, height//2)], fill='white', width=2)
        elif style == 'vibrant':
            # Add vibrant elements
            import random
            for _ in range(10):
                x = random.randint(50, width-50)
                y = random.randint(50, height-50)
                draw.rectangle([(x-10, y-10), (x+10, y+10)], fill='white')
    
    def wrap_text(self, text, max_width, font):
        """Wrap text to fit within max_width"""
        lines = []
        words = text.split()
        current_line = []
        
        for word in words:
            current_line.append(word)
            test_line = ' '.join(current_line)
            # Get text width (approximate)
            test_width = len(test_line) * 12  # Rough estimate
            if test_width > max_width:
                if len(current_line) == 1:
                    lines.append(test_line)
                    current_line = []
                else:
                    current_line.pop()
                    lines.append(' '.join(current_line))
                    current_line = [word]
        
        if current_line:
            lines.append(' '.join(current_line))
        
        return lines
